name: eslint

on: [push]

jobs:
  eslint check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Make Lint
        run: make lint
