name: jest

on: [push]

jobs:
  jest check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Make Test
        run: make test
